export class LoginModel {
  Email: string;
  Password: string;
  RememberMe: boolean;
}
export class RegisterViewModel {
  Email: string;
  Password: string;
  ConfirmPassword: string;
  Firstname: string;
  Lastname: string;
  BirthdayDay: number;
  BirthdayMonth: number;
  BirthdayYear: number;
  Sex: boolean;
  PhoneNumber: string;
}

// Generated by https://quicktype.io

export class UserViewModel {
  Id: string;
  UserName: string;
  Email: string;
  Fullname: string;
  Birthday: string;

  Firstname?: any;
  Lastname?: any;

  Sex: boolean;
  SexString: string;
  BirthdayDay: number;
  BirthdayMonth: number;
  BirthdayYear: number;

  Slogan: string;
  PhoneNumber: null;


}
// Generated by https://quicktype.io

export class TokenViewModel {
  token: string;
}
